#!/bin/bash

#Project specific URL
registry=$1

tags="kernel microProfile1 microProfile2 microProfile3 springBoot1 springBoot2 webProfile7 javaee7 webProfile8 javaee8"

for tag in $tags; do
  echo "****** Pushing ${tag}"
  cd ${tag}
  image="websphere-liberty:${tag}-ubi-min"
  docker build -t ${image} -f Dockerfile.ubi-min .
  docker tag ${image} scan.connect.redhat.com/${registry}/${image}
  docker push scan.connect.redhat.com/${registry}/${image}
  cd ..
done
