#!/bin/bash
tag=$1
dockerfile=$2

if [ -z "$tag" ]; then
   tag="kernel"
fi

if [ -z "$dockerfile" ]; then
   dockerfile="Dockerfile.rhel"
fi

docker create --name wlpcontainer websphere-liberty:$tag
docker cp wlpcontainer:/opt/ibm .
docker rm -f wlpcontainer > /dev/null 2>&1
docker rmi -f wlp-rhel:$tag > /dev/null 2>&1
docker build -t wlp-rhel:$tag -f $dockerfile .
rm -rf ibm
