# This is a basic workflow that is manually triggered

name: vNext manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      OLD_VERSION:
        description: 'Enter old version'
        # Default value if no value is explicitly provided
        default: '23.0.0.11'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      NEW_VERSION:
        description: 'Enter new version'
        default: '23.0.0.12'
        required: true
        type: string
      OLD_SHORT_VERSION:
        description: 'Enter single digit of old version'
        default: '11'
        required: true
        type: string
      BUILD_LABEL:
        description: 'Enter build label of release driver'
        default: ''
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "OLD_VERSION ${{ inputs.OLD_VERSION }}"
        echo "NEW_VERSION ${{ inputs.OLD_VERSION }}"
        echo "OLD_SHORT_VERSION ${{ inputs.OLD_SHORT_VERSION }}"
        echo "BUILD_LABEL ${{ inputs.BUILD_LABEL }}"
