# This is a basic workflow that is triggered by a push

name: Update files for new release workflow

on:
  push:
    branches:
      - vNext
    paths:
      - 'vNext.properties'

env:
  NEW_VERSION: 23.0.0.73

jobs:
  automate_release_updates:
    runs-on: ubuntu-latest

    steps:
    - name: Show useful information about the environment
      run: |
        echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        env

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        ref: vNext
        repository: wraschke/ci.docker

    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

    - name: Run update.sh script
      run: bash ./update.sh

    - run: echo "NEW_VERSION = ${{ env.NEW_VERSION }}"

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with: 
        default_author: github_actions
        author_name: GitHub Actions
        author_email: mail@example.com
        message: "Updates for the release of ${{ env.NEW_VERSION }}"
        add: '${{ github.workspace }}/ga/*'
        new_branch: "${{ env.NEW_VERSION }}-release"
        push: true
        tag_push: '--force'

    - name: Create Pull Request
      run: |
        echo "NEW_VERSION = ${{ env.NEW_VERSION }}"
        gh pr create -B vNext -H "${{ env.NEW_VERSION }}-release" -r mbroz2 -r leochr --title "Updates for the release of ${{ env.NEW_VERSION }}" --body "Created by Github Actions"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "🍏 This job's status is ${{ job.status }}."
